### PR TITLE
If we get an unknown mutator log an error and continue

### PR DESCRIPTION
**Pull request by arv**

### CODE REVIEW

**Comment by arv** [comment]
Same here...

**Comment by aboodman** [comment]
Eep, OK. We should have a test for this in both sdks. This is an important one.

**Comment by aboodman** [comment]
Basically anything that can stop sync is important. Having sync wedge is one of the worst failure modes of this kind of product.

**Comment by aboodman** [comment]
@phritz seems like a product/company value we should write down somewhere:

- Rocicorp product won't crash your app
- Replicache won't stop syncing. It's like one of those scary robot dog things. You can kick it, it might wobble for a second, but then it gets back up and carries on along its path.

**Pull request merged**
